services:
  - type: web
    name: fileflip-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: FRONTEND_URL
        fromGroupSecret: FRONTEND_URL

  - type: static
    name: fileflip-frontend
    buildCommand: npm run build
    publishDirectory: dist
    envVars:
      - key: VITE_API_URL
        fromGroupSecret: API_URL
